// @TODO - Remove as these are test data structure
export const messages = [
  {
    action: 0,
    message: 'Item sold!',
    user: 123,
    userName: 'User 1',
    userThumbnail: 'https://picsum.photos/50/50',
    product: 'Item 1',
  },
  {
    action: 1,
    message: 'Yahoo',
    user: 123,
    userName: 'User 2',
    userThumbnail: 'https://picsum.photos/50/50',
    product: 'Item 1',
  },
  {
    action: 2,
    message: 'Yahoo',
    user: 123,
    userName: 'User 3',
    userThumbnail: 'https://picsum.photos/50/50',
    product: 'Item 1',
  },
  {
    action: 0,
    message: 'Item sold!',
    user: 123,
    userName: 'User 4',
    userThumbnail: 'https://picsum.photos/50/50',
    product: 'Item 1',
  },
  {
    action: 0,
    message: 'Item sold!',
    user: 123,
    userName: 'User 5',
    userThumbnail: 'https://picsum.photos/50/50',
    product: 'Item 1',
  },
  {
    action: 1,
    message: 'Yahoo',
    user: 123,
    userName: 'User 6',
    userThumbnail: 'https://picsum.photos/50/50',
    product: 'Item 1',
  },
  {
    action: 2,
    message: 'Yahoo',
    user: 123,
    userName: 'User 7',
    userThumbnail: 'https://picsum.photos/50/50',
    product: 'Item 1',
  },
  {
    action: 2,
    message: 'Yahoo',
    user: 123,
    userName: 'User 8',
    userThumbnail: 'https://picsum.photos/50/50',
    product: 'Item 1',
  },
  {
    action: 2,
    message: 'Yahoo',
    user: 123,
    userName: 'User 9',
    userThumbnail: 'https://picsum.photos/50/50',
    product: 'Item 1',
  },
  {
    action: 2,
    message: 'Yahoo',
    user: 123,
    userName: 'User 10',
    userThumbnail: 'https://picsum.photos/50/50',
    product: 'Item 1',
  },
];

export const actionTypeMessage = {
  0: 'BUY',
  1: 'ASK',
  2: 'BID',
};
